### ISSUE TITLE
Document deployment of the MED-Portal

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/MED-Portal#2]
We need a document explaining how to deploy the MED-Portal. 
We need a list of requirements.
We also need a way to share credentials.

**Comment by max-anu** [comment]
This is from memory: The instructions on the github pages for joss/thoej were mostly fine once you knew how heroku worked.
From memory, the main issues I ran into when I was doing my own version were:
* Have all the necessary services working on heroku.
* Ensure the github secrets and environment variables match where they should.
* Make sure that you have created all the necessary repos (there were a bunch). For example:
  * repo to store the pdfs
  * repo for github actions
  * make a clone of certain repos to change default values - e.g. some of the actions had hardcoded values which were specific to joss and could not be changed.
